#
version: '2'
networks:
  bymn:
services:


      orderer0.example.com:
        container_name: orderer0.example.com
        image: hyperledger/fabric-orderer
        environment:
          - ORDERER_HOME=/tmp/hyperledger/orderer
          - ORDERER_HOST= orderer0.example.com
          - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
          - ORDERER_GENERAL_GENESISMETHOD=file
          - ORDERER_GENERAL_GENESISFILE=/tmp/hyperledger/org0/orderer/genesis.block
          - ORDERER_GENERAL_LOCALMSPID=org0MSP
          - ORDERER_GENERAL_LOCALMSPDIR=/tmp/hyperledger/org0/orderer/msp
          - ORDERER_GENERAL_TLS_ENABLED=true
          - ORDERER_GENERAL_TLS_CERTIFICATE=/tmp/hyperledger/org0/orderer/assets/tls-msp/signcerts/cert.pem
          - ORDERER_GENERAL_TLS_PRIVATEKEY=/tmp/hyperledger/org0/orderer/assets/tls-msp/keystore/key.pem
          - ORDERER_GENERAL_TLS_ROOTCAS=[/tmp/hyperledger/org0/orderer/assets/tls-msp/tlscacerts/tls-0-0-0-0-7052.pem]
          - ORDERER_GENERAL_LOGLEVEL=debug
          - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
        volumes:
          - /home/simran/go/src/github.com/hyperledger/fabric-ca/tmp2/hyperledger/org0:/tmp/hyperledger/org0/
        ports:
          - 7050:7050
        networks:
          - bymn   