rca-org2:
   container_name: rca-org2
   image: hyperledger/fabric-ca
   command: /bin/bash -c 'fabric-ca-server start -d -b rca-org2-admin:rca-org2-adminpw'
   environment:
      - FABRIC_CA_SERVER_HOME=/tmp/hyperledger/fabric-ca/crypto
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org1
      - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
      - FABRIC_CA_SERVER_DEBUG=true
   volumes:
      - /home/simran/go/src/github.com/hyperledger/fabric-ca/tmp2/hyperledger/org2/ca:/tmp/hyperledger/fabric-ca
   
   ports:
      - 10054:10054